In [2]:
import pandas as pd
import numpy as np

In [6]:
data_files = {
    'sessions': ('session_time',),
    'trips': ('pickup_time', 'dropoff_time'),
    'riders': ('signup_date',),
    'drivers': ('signup_date', 'last_active'),
    'promotions': ('start_date', 'end_date')
}

dfs = {}
for name, date_cols in data_files.items():
    dfs[name] = pd.read_csv(f'../data/raw/{name}.csv', parse_dates=list(date_cols))

In [30]:
dfs['sessions'].head()

,session_id,rider_id,session_time,time_on_app,pages_visited,converted,city,loyalty_status
0,S000000,R08605,2025-04-27 18:57:06+02:05,79,4,1,Cairo,Bronze
1,S000001,R08823,2025-04-27 07:32:22+02:27,101,3,0,Nairobi,Silver
2,S000002,R05342,2025-04-27 23:17:25+02:05,12,1,0,Cairo,Bronze
3,S000003,R05057,2025-04-27 14:40:25+00:14,19,1,0,Lagos,Silver
4,S000004,R09614,2025-04-27 08:31:22+00:14,4,1,0,Lagos,Bronze

In [13]:
dfs['sessions'].info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   session_id      50000 non-null  str
 1   rider_id        50000 non-null  str
 2   session_time    50000 non-null  str
 3   time_on_app     50000 non-null  int64
 4   pages_visited   50000 non-null  int64
 5   converted       50000 non-null  int64
 6   city            50000 non-null  str
 7   loyalty_status  50000 non-null  str
dtypes: int64(3), str(5)
memory usage: 3.1 MB

In [14]:
dfs['sessions'].duplicated().sum()

np.int64(0)

In [32]:
dfs['sessions']['session_time'] = pd.to_datetime(dfs['sessions']['session_time'], utc=True, errors='coerce')

In [33]:
dfs['sessions']['session_time'].dtype

datetime64[us, UTC]

In [34]:
for col in dfs['sessions'].select_dtypes(include=['str', 'bool']).columns.tolist():
    print(dfs['sessions'][col].value_counts())
    print('-----------------------------')

session_id
S000000    1
S000001    1
S000002    1
S000003    1
S000004    1
          ..
S049995    1
S049996    1
S049997    1
S049998    1
S049999    1
Name: count, Length: 50000, dtype: int64
-----------------------------
rider_id
R03390    16
R08301    16
R00790    14
R08968    14
R03955    14
          ..
R05131     1
R02639     1
R07676     1
R05582     1
R00358     1
Name: count, Length: 9929, dtype: int64
-----------------------------
city
Cairo      16967
Nairobi    16598
Lagos      16435
Name: count, dtype: int64
-----------------------------
loyalty_status
Bronze      30298
Silver      12170
Gold         5197
Platinum     2335
Name: count, dtype: int64
-----------------------------

In [35]:
dfs['riders'].head()

,user_id,signup_date,loyalty_status,age,city,avg_rating_given,churn_prob,referred_by
0,R00000,2025-01-24,Bronze,34.729629,Nairobi,5.0,0.142431,R00001
1,R00001,2024-09-09,Bronze,34.571020,Nairobi,4.7,0.674161,NaN
2,R00002,2024-09-07,Bronze,47.133960,Lagos,4.2,0.510379,NaN
3,R00003,2025-03-17,Bronze,41.658628,Nairobi,4.9,0.244779,NaN
4,R00004,2024-08-20,Silver,40.681709,Lagos,3.9,0.269960,R00002

In [60]:
dfs['riders'].info()
print('-----------------------------')
dfs['riders'].duplicated().sum()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   user_id           10000 non-null  str
 1   signup_date       10000 non-null  datetime64[us]
 2   loyalty_status    10000 non-null  str
 3   age               10000 non-null  float64
 4   city              10000 non-null  str
 5   avg_rating_given  10000 non-null  float64
 6   churn_prob        10000 non-null  float64
 7   referred_by       10000 non-null  str
dtypes: datetime64[us](1), float64(3), str(4)
memory usage: 625.1 KB
-----------------------------

np.int64(0)

In [38]:
for col in dfs['riders'].select_dtypes(include=['str', 'bool']).columns.tolist():
    print(dfs['riders'][col].value_counts())
    print('-----------------------------')

user_id
R00000    1
R00001    1
R00002    1
R00003    1
R00004    1
         ..
R09995    1
R09996    1
R09997    1
R09998    1
R09999    1
Name: count, Length: 10000, dtype: int64
-----------------------------
loyalty_status
Bronze      6057
Silver      2425
Gold        1050
Platinum     468
Name: count, dtype: int64
-----------------------------
city
Cairo      3374
Nairobi    3330
Lagos      3296
Name: count, dtype: int64
-----------------------------
referred_by
R00002    46
R00001    33
R00033    32
R00030    24
R00021    22
          ..
R08187     1
R08370     1
R09768     1
R02155     1
R07447     1
Name: count, Length: 1660, dtype: int64
-----------------------------

In [39]:
dfs['riders']['referred_by'] = dfs['riders']['referred_by'].fillna('unknown')
dfs['riders'].head()

,user_id,signup_date,loyalty_status,age,city,avg_rating_given,churn_prob,referred_by
0,R00000,2025-01-24,Bronze,34.729629,Nairobi,5.0,0.142431,R00001
1,R00001,2024-09-09,Bronze,34.571020,Nairobi,4.7,0.674161,unknown
2,R00002,2024-09-07,Bronze,47.133960,Lagos,4.2,0.510379,unknown
3,R00003,2025-03-17,Bronze,41.658628,Nairobi,4.9,0.244779,unknown
4,R00004,2024-08-20,Silver,40.681709,Lagos,3.9,0.269960,R00002

In [40]:
dfs['trips'].head()

,trip_id,user_id,driver_id,fare,surge_multiplier,tip,payment_type,pickup_time,dropoff_time,pickup_lat,pickup_lng,dropoff_lat,dropoff_lng,weather,city,loyalty_status
0,T000000,R05207,D00315,12.11,1.0,0.00,Card,2024-11-27 18:41:50+02:27,2024-11-27 19:33:50+02:27,-1.108123,36.912209,-1.068155,36.875377,Foggy,Nairobi,Bronze
1,T000001,R09453,D03717,8.73,1.0,0.02,Card,2024-10-28 23:13:48+00:14,2024-10-28 23:26:48+00:14,6.675266,3.515740,6.641734,3.525620,Sunny,Lagos,Gold
2,T000002,R00567,D02035,19.68,1.0,0.00,Card,2025-02-17 05:36:41+02:27,2025-02-17 05:52:41+02:27,-1.248589,37.010668,-1.273182,37.018586,Cloudy,Nairobi,Bronze
3,T000003,R09573,D02657,16.43,1.0,0.01,Mobile Money,2024-06-18 19:27:14+02:05,2024-06-18 19:32:14+02:05,29.819554,31.188780,29.837689,31.232978,Cloudy,Cairo,Bronze
4,T000004,R03446,D01026,8.70,1.0,1.06,Card,2024-10-05 09:58:16+02:27,2024-10-05 10:28:16+02:27,-1.676479,36.729219,-1.638395,36.694063,Sunny,Nairobi,Gold

In [42]:
dfs['trips'].info()
print('-----------------------------')
dfs['trips'].duplicated().sum()

<class 'pandas.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 16 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   trip_id           200000 non-null  str
 1   user_id           200000 non-null  str
 2   driver_id         200000 non-null  str
 3   fare              200000 non-null  float64
 4   surge_multiplier  200000 non-null  float64
 5   tip               200000 non-null  float64
 6   payment_type      200000 non-null  str
 7   pickup_time       200000 non-null  str
 8   dropoff_time      200000 non-null  str
 9   pickup_lat        200000 non-null  float64
 10  pickup_lng        200000 non-null  float64
 11  dropoff_lat       200000 non-null  float64
 12  dropoff_lng       200000 non-null  float64
 13  weather           200000 non-null  str
 14  city              200000 non-null  str
 15  loyalty_status    200000 non-null  str
dtypes: float64(7), str(9)
memory usage: 24.4 MB
-----------------------------

np.int64(0)

In [47]:
dfs['trips'][['pickup_time', 'dropoff_time']] = dfs['trips'][['pickup_time', 'dropoff_time']].apply(
    pd.to_datetime, utc=True, errors='coerce'
)

In [48]:
dfs['trips'][['pickup_time', 'dropoff_time']].dtypes

pickup_time     datetime64[us, UTC]
dropoff_time    datetime64[us, UTC]
dtype: object

In [59]:
for col in dfs['trips'].select_dtypes(include=['str']).columns.tolist():
    print(dfs['trips'][col].value_counts())
    print('-----------------------------')

trip_id
T000000    1
T000001    1
T000002    1
T000003    1
T000004    1
          ..
T199995    1
T199996    1
T199997    1
T199998    1
T199999    1
Name: count, Length: 200000, dtype: int64
-----------------------------
user_id
R08152    42
R06728    39
R09210    38
R09908    37
R00739    37
          ..
R01782     7
R06836     7
R00197     6
R01184     6
R03232     6
Name: count, Length: 10000, dtype: int64
-----------------------------
driver_id
D03093    67
D01999    66
D01107    65
D02137    65
D02429    63
          ..
D01358    21
D04432    21
D01250    21
D04528    19
D00728    19
Name: count, Length: 5000, dtype: int64
-----------------------------
payment_type
Card            100326
Mobile Money     79661
Cash             20013
Name: count, dtype: int64
-----------------------------
weather
Sunny     120151
Rainy      39976
Cloudy     29874
Foggy       9999
Name: count, dtype: int64
-----------------------------
city
Cairo      67436
Nairobi    66705
Lagos      65859
Name: count, dtype: int64
-----------------------------
loyalty_status
Bronze      121252
Silver       48332
Gold         21044
Platinum      9372
Name: count, dtype: int64
-----------------------------

In [50]:
dfs['promotions'].head()

,promo_id,promo_name,promo_type,promo_value,start_date,end_date,target_segment,city_scope,ab_test_groups,test_allocation,success_metric
0,P000,Peak Hour Pass,surge_waiver,1.0,2025-04-26,2025-05-25,All,Nairobi,['All'],[1.0],Usage Frequency
1,P001,Peak Hour Pass,surge_waiver,1.0,2025-04-26,2025-05-22,All,Cairo,"['Control', 'Variant A', 'Variant B']","[0.3, 0.4, 0.3]",Conversion Rate
2,P002,Peak Hour Pass,surge_waiver,1.0,2025-04-26,2025-05-16,All,Cairo,"['Control', 'Variant A', 'Variant B']","[0.3, 0.4, 0.3]",ROI
3,P003,Loyalty Bonus,points,100.0,2025-04-26,2025-05-04,Gold+,Nairobi,"['Control', 'Variant A', 'Variant B']","[0.3, 0.4, 0.3]",Conversion Rate
4,P004,Loyalty Bonus,points,100.0,2025-04-26,2025-05-15,Gold+,Nairobi,['All'],[1.0],Usage Frequency

In [51]:
dfs['promotions'].info()
print('-----------------------------')
dfs['promotions'].duplicated().sum()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   promo_id         20 non-null     str
 1   promo_name       20 non-null     str
 2   promo_type       20 non-null     str
 3   promo_value      20 non-null     float64
 4   start_date       20 non-null     datetime64[us]
 5   end_date         20 non-null     datetime64[us]
 6   target_segment   20 non-null     str
 7   city_scope       20 non-null     str
 8   ab_test_groups   20 non-null     str
 9   test_allocation  20 non-null     str
 10  success_metric   20 non-null     str
dtypes: datetime64[us](2), float64(1), str(8)
memory usage: 1.8 KB
-----------------------------

np.int64(0)

In [58]:
for col in dfs['promotions'].select_dtypes(include=['str']).columns.tolist():
    print(dfs['promotions'][col].value_counts())
    print('-----------------------------')

promo_id
P000    1
P001    1
P002    1
P003    1
P004    1
P005    1
P006    1
P007    1
P008    1
P009    1
P010    1
P011    1
P012    1
P013    1
P014    1
P015    1
P016    1
P017    1
P018    1
P019    1
Name: count, dtype: int64
-----------------------------
promo_name
First Ride Discount    8
Peak Hour Pass         5
Loyalty Bonus          5
Referral Special       2
Name: count, dtype: int64
-----------------------------
promo_type
discount        8
surge_waiver    5
points          5
credit          2
Name: count, dtype: int64
-----------------------------
target_segment
New       8
All       5
Gold+     5
Active    2
Name: count, dtype: int64
-----------------------------
city_scope
Nairobi       6
Lagos         5
All-Cities    5
Cairo         4
Name: count, dtype: int64
-----------------------------
ab_test_groups
['All']                                  10
['Control', 'Variant A', 'Variant B']    10
Name: count, dtype: int64
-----------------------------
test_allocation
[1.0]              10
[0.3, 0.4, 0.3]    10
Name: count, dtype: int64
-----------------------------
success_metric
ROI                10
Usage Frequency     6
Conversion Rate     4
Name: count, dtype: int64
-----------------------------

In [53]:
dfs['drivers'].head()

,driver_id,rating,vehicle_type,signup_date,last_active,city,acceptance_rate
0,D00000,3.1,SUV,2025-01-20,2025-01-06 18:23:09.312275,Cairo,0.679555
1,D00001,5.0,Sedan,2023-03-27,2025-04-27 01:44:02.472554,Nairobi,0.548786
2,D00002,4.5,Motorcycle,2024-05-02,2025-03-07 19:24:46.367672,Nairobi,0.593724
3,D00003,5.0,Motorcycle,2023-04-16,2025-03-26 19:16:24.253793,Nairobi,0.990000
4,D00004,4.4,Motorcycle,2023-05-28,2025-04-08 18:54:44.649615,Lagos,0.519773

In [54]:
dfs['drivers'].info()
print('-----------------------------')
dfs['drivers'].duplicated().sum()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   driver_id        5000 non-null   str
 1   rating           5000 non-null   float64
 2   vehicle_type     5000 non-null   str
 3   signup_date      5000 non-null   datetime64[us]
 4   last_active      5000 non-null   datetime64[us]
 5   city             5000 non-null   str
 6   acceptance_rate  5000 non-null   float64
dtypes: datetime64[us](2), float64(2), str(3)
memory usage: 273.6 KB
-----------------------------

np.int64(0)

In [57]:
for col in dfs['drivers'].select_dtypes(include=['str']).columns.tolist():
    print(dfs['drivers'][col].value_counts())
    print('-----------------------------')

driver_id
D00000    1
D00001    1
D00002    1
D00003    1
D00004    1
         ..
D04995    1
D04996    1
D04997    1
D04998    1
D04999    1
Name: count, Length: 5000, dtype: int64
-----------------------------
vehicle_type
Sedan         2439
SUV           1742
Motorcycle     675
Luxury         144
Name: count, dtype: int64
-----------------------------
city
Lagos      1720
Nairobi    1709
Cairo      1571
Name: count, dtype: int64
-----------------------------